### PR TITLE
Zendesk Header and Footer

### PR DESCRIPTION
**Pull request by arslanashraf7**
## Relevant Tickets
#4 
#3 

**Live view of this theme can be seen [here](https://arslantest.zendesk.com/hc/en-us)**

## What does this PR do?

- Upgrades the theme repo to contain all the files that would be required for the development/testing of our custom theme
- Upgrades the theme to 2.8.0 from 1.5.0
- Adds Bootcamp matching header
- Adds Bootcamp matching footer

**Screenshots**
**(DESKTOP)**
**Header**

Screenshot 2021-03-09 at 5 53 47 PM

**Footer**
Screenshot 2021-03-09 at 5 53 18 PM

**(MOBILE)**

**Header**
Screenshot 2021-03-09 at 5 53 37 PM

**Footer**
Screenshot 2021-03-09 at 5 53 28 PM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@briangrossman, Could you please take a look at the screenshots attached and there is also a link to test this theme on one of the test accounts, Let me know what are your thoughts on this.

Also, there is a small question, In the main application when the user clicks on `Help & FAQ` link, we're redirecting the user to the homepage of Zendesk but in the case of this theme when the user is already on Zendesk, Where should we redirect him/her?

**Comment by briangrossman** [comment]
@arslanashraf7 
These look good. A few comments / questions:
- **Header:** We should remove the `Submit a request` from the header
- **Header:** I was assuming that we wouldn't be able to include the `Sign in` in the header as we won't be able to have it behave the way it works on the rest of the site. 
- **Footer:** I'm assuming that the form for Hubspot (First/Last/Company/Job Title/Email) in the footer will be replaced with the simpler form on production (see image below) 
image
- In terms of `Help & FAQ`, I think it should just go to the same page (Zendesk homepage) for consistency.

**Comment by arslanashraf7** [comment]
@briangrossman, I've addressed the feedback from your last comment and I've also updated the screenshots in the description. The test theme [link](https://arslantest.zendesk.com/hc/en-us) is also running the latest theme changes.

>Header: I was assuming that we wouldn't be able to include the Sign in in the header as we won't be able to have it behave the way it works on the rest of the site.

As for the above point, the `Sign in` in this case was based on Zendesk's account which is independent of our Bootcamp's user account I've just removed it in favor of the discussion we had https://github.com/mitodl/bootcamps-zendesk-theme/issues/4#issuecomment-791544847.

Please let me know your thoughts on the updated theme.

**Comment by briangrossman** [comment]
@arslanashraf7 
Yup! Looks good to me. Thanks!

I assume the hamburger nav on mobile would only contain 'How to Apply', correct? (Here's what it looks like on my phone)
110496940-002fa580-80c4-11eb-8cbd-1b07cc1d14e2

**Comment by arslanashraf7** [comment]
@briangrossman Correct, Although it was left-aligned, I've just added the style to align it on right. Adding both 
the screenshots below and you can see that change on the test theme link as well.

(When it was aligned left)
Screenshot 2021-03-10 at 12 15 53 PM

(Current: Aligned it right)

Screenshot 2021-03-10 at 12 20 52 PM

**Review by HamzaIbnFarooq — APPROVED** [review]
LG on dev account.

**Pull request merged**
